#
FROM node:16.5.0-alpine3.11 as main
#give name if youre going to use main on copy for example instead of 0

# WORK FOLDER
WORKDIR /app  

# Copy first the package json, else it will rerun ALL the installs, bad idea
COPY ./package.json ./
RUN npm install
COPY ./ ./
RUN npm run build 

# Bug do eslint não encontrado
RUN chown node:node /app/node_modules/.cache/.eslintcache

CMD ["npm","run","start"]
# Parece que o NGINX bloqueia o client de utilizar volume, então para Dev é melhor retirar ele.
# FROM nginx 
EXPOSE 80
# expose é do beanstalk ou melhor, qualquer cloud service
# COPY --from=main  /client/build /usr/share/nginx/html 

# drwxr-xr-x 
# drwxr-xr-x